### ISSUE TITLE
Using other fields from the User Class

### ISSUE THREAD

**Issue by ialameh** [macarthuror/parse-smtp-template#11]
Hi,
Can I use other fields from the user class within the template? like firstname lastname and so on?

Sam

**Comment by ialameh** [comment]
or at least can the extra options be a response from an api

**Comment by macarthuror** [comment]
Hello @ialameh ,

Yes, you can access other parameters of the user using the [_multi-template_](https://github.com/macarthuror/parse-smtp-template#multi-template) option.

**Comment by ialameh** [comment]
please can you provide an example
if I have a field firstName in  the Users class how I can access that

**Comment by macarthuror** [comment]
Sure, in that case you need to use `${user.firstName}` in the html file.
