### ISSUE TITLE
Multi language "others" parameters issue

### ISSUE THREAD

**Issue by Meglali20** [macarthuror/parse-smtp-template#18]
When trying to use multi-language and multi templates, I get the following error 

`
error: Uncaught internal server error. Cannot read properties of undefined (reading 'others') {"stack":"TypeError: Cannot read properties of undefined (reading 'others')\n    at Object.sendPasswordResetEmail (C:\\Users\\megla\\AppData\\Roaming\\npm\\node_modules\\parse-smtp-template\\index.js:275:119)\n    at UserController.sendPasswordResetEmail (C:\\Users\\megla\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Controllers\\UserController.js:303:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
TypeError: Cannot read properties of undefined (reading 'others')
    at Object.sendPasswordResetEmail (C:\Users\megla\AppData\Roaming\npm\node_modules\parse-smtp-template\index.js:275:119)
    at UserController.sendPasswordResetEmail (C:\Users\megla\AppData\Roaming\npm\node_modules\parse-server\lib\Controllers\UserController.js:303:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

did follow the same instructions in the [ReadMe](https://github.com/macarthuror/parse-smtp-template/blob/master/README.md)

I keep getting the same error with and without "others" 

using signal template works without any issue.

I would also like to know something, how can you determine the language of the receiver? also, a feature request would be to create multiple files for each language since those are mostly static why not just pick a single file for each language instead.

**Comment by macarthuror** [comment]
Could you add the version of Parse and the configuration are using ?

**Comment by Meglali20** [comment]
parse server version: parse-server@5.0.0-alpha.3

```
"emailAdapter": {
        "module": "parse-smtp-template",
        "options": {
            "multiTemplate": true,
            "confirmTemplatePath": "/views/confirmTemplate.html",
            "passwordTemplatePath": "/views/passwordTemplate.html",
            "multiLang": true,
            "multiLangPass": {
                "es": {
                    "subject": "Recuperación de Contraseña",
                    "body": "Cuerpo del correo de recuperación de contrseña",
                    "btn": "recupera tu contraseña"
                },
                "en": {
                    "subject": "Password recovery",
                    "body": "Password recovery email body",
                    "btn": "Recover your password"
                },
                "fr": {
                    "subject": "Récupération du mot de passe",
                    "body": "Corps de l'e-mail de récupération de mot de passe",
                    "btn": "récupérer votre mot de passe"
                }
            },
            "multiLangConfirm": {
                "es": {
                    "subject": "Confirmación de Correo",
                    "body": "Cuerpo del correo de confirmación de correo",
                    "btn": "confirma tu correo"
                },
                "en": {
                    "subject": "E-mail confirmation",
                    "body": "Mail confirmation email body",
                    "btn": "confirm your email"
                },
                "fr": {
                    "subject": "Mail de confirmation",
                    "body": "Courriel de confirmation du corps de l'e-mail",
                    "btn": "confirmez votre email"
                }
            },
            "passwordOptions": {
                "subject": "Password recovery",
                "body": "Custome pasword recovery email body",
                "btn": "Recover your password"
            },
            "confirmOptions": {
                "subject": "E-mail confirmation",
                "body": "Custome email confirmation body",
                "btn": "confirm your email"
            },
            "port": 465,
            "host": "",
            "user": "",
            "password": "",
            "secure": true,
            "fromAddress": ""
        }
    }
```

**Comment by macarthuror** [comment]
The error is because you're using the variable `others` in the template (apparently) but is not in your config.

Please check about _Extra Parameters_ in the [docs](https://github.com/macarthuror/parse-smtp-template/blob/master/README.md)

**Comment by Meglali20** [comment]
I am not using "others" variable in the template. the template is the same as provided in this repo.
Even adding "others" parameters in the config file doesn't solve the issue, as I mentioned I did follow the docs and tried with and without parameters.

**Comment by macarthuror** [comment]
I will try to replicate this issue.
What version of node are you using?

**Comment by Meglali20** [comment]
parse server version: parse-server@5.0.0-alpha.3
node version: 16.13.1
npm version: 8.3.0

**Comment by martinatwainobicom** [comment]
I have the same issue with 
parse-server version: 4.10.4

I have set up the language column in the _User table but it seems, that the user object passed into "sendVerificationEmail", does not contain the language column and therefore fails.

**Comment by Meglali20** [comment]
Any update on this?

**Comment by sadnflame** [comment]
I found the reason ： the user object which you saved need to set the "lang" attribute, otherwise the file parse-smtp-template\\index.js  just get the user object without the lang attribute and cause the exception. 
Here is the example：
  ```
const objid = request.params.objectId
  const query = new Parse.Query(Parse.User);
  query.equalTo("objectId", objid);
  try {
    const user = await query.first({ useMasterKey: true });
    user.set("username", request.params.username)
    user.set("firstname", request.params.firstname)
    user.set("lastname", request.params.lastname)
    user.set("phone", request.params.phone)
    user.set("group", request.params.group)
    user.set("lang",request.params.lang)
    await user.save(null, { context: { userID: request.user.id }, useMasterKey: true });
  } catch (e) {
    flag = false
    console.log(e);
  }
```

**Comment by macarthuror** [comment]
@sadnflame Could you make a Pull Request with the fix changes?

**Comment by sadnflame** [comment]
> @sadnflame Could you make a Pull Request with the fix changes?

@macarthuror  It doesn't need to make a Pull Request.
Before saving the Parse.User , just need to add the 'lang' attribute into the User Object, then fix the issue.
```
user.set("lang",request.params.lang)
await user.save(null, { context: { userID: request.user.id }, useMasterKey: true });
```

**Comment by macarthuror** [comment]
Solved by @sadnflame
