### ISSUE TITLE
Adding Extra Parameters not working

### ISSUE THREAD

**Issue by maleksalem** [macarthuror/parse-smtp-template#2]
Hello, 
I am trying to add some extra parameters to my config file and template but it is not working out fine. 
     "multiLangConfirm": {
      
      "en": {
        "subject": "E-mail confirmation",
        "body": "Mail confirmation email body",
        "btn": "confirm your email",
        "others": {
          "footer": "Thank you!"
        }
        
      },
     
     
In the HTML template confirmTemplate.html I am adding ${others.footer}
Please let me know if this works or the correct way that it works with.

Thanks

**Comment by macarthuror** [comment]
Hello @maleksalem,
Could you please paste all the email adapter code, to check it.
Thanks.

**Comment by macarthuror** [comment]
If the problem is still there please let me know to fix it. Thanks 😁👌

**Comment by macarthuror** [comment]
@maleksalem I believe that the problem may be the use of quotes in the variables.

Could you please try to use it like this:

``` javascript
en: {
    subject: "E-mail confirmation",
    body: "Mail confirmation email body",
    btn: "confirm your email",
    others: {
      footer: "Thank you!"
    }
    
  },
```
