### ISSUE TITLE
Support 'default' language

### ISSUE THREAD

**Issue by oproulx** [macarthuror/parse-smtp-template#21]
When a user has the 'multiLangColumn' property set to a value that is not in the list (in multiLangPass for example), we get a 500 error.

Example: 

For: 
user.get('lang') = 'es'

multiLangPass: {
          en: {
            subject: "Password Reset",
            body: "Somebody (hopefully you) requested a new password.",
            btn: "Reset your password"
          },
          fr: {
            subject: "Réinitialiser votre mot de passe",
            body: "Quelqu'un a demandé un nouveau mot de passe pour votre compte.",
            btn: "Réinitialiser votre mot de passe"
          }
        },

This throws a 500.

**Comment by oproulx** [comment]
error: Uncaught internal server error. Cannot read property 'others' of undefined {"stack":"TypeError: Cannot read property 'others' of undefined\n    at Object.sendPasswordResetEmail (D:\\home\\site\\wwwroot\\node_modules\\parse-smtp-template\\index.js:275:119)\n    at UserController.sendPasswordResetEmail (D:\\home\\site\\wwwroot\\node_modules\\parse-server\\lib\\Controllers\\UserController.js:295:20)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:94:5)"}

TypeError: Cannot read property 'others' of undefined
    at Object.sendPasswordResetEmail (D:\home\site\wwwroot\node_modules\parse-smtp-template\index.js:275:119)
    at UserController.sendPasswordResetEmail (D:\home\site\wwwroot\node_modules\parse-server\lib\Controllers\UserController.js:295:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

The issue seems to be on this line:
        const options = (_multiLang && mailOptions.multiLangPass) ? mailOptions.multiLangPass[user[_multiLangColumn]].others || {} : mailOptions.passwordOptions.others || {};

It seems there needs to be a check to make sure that mailOptions.multiLangPass[user[_multiLangColumn]] != 'undefined'

**Comment by oproulx** [comment]
After yet another look, it seems like const options is never used.  I will try to remove it.

**Comment by macarthuror** [comment]
Solved in #22
