### ISSUE TITLE
URL encoded email address in username parameter

### ISSUE THREAD

**Issue by vmkudrin** [macarthuror/parse-smtp-template#3]
When email address is used as user name in Parse server, HTML template is filled with url-encoded email by ${username} parameter (ex. user%40mail.com)

**Comment by macarthuror** [comment]
Thanks, let me try it.
Anyway if you want to do a pull request is welcome 😁

**Comment by macarthuror** [comment]
@vmkudrin It's solve, Thanks for open the issue and for the wait 😅😁
