### ISSUE TITLE
Any way to set "From" name

### ISSUE THREAD

**Issue by ravikiranp123** [macarthuror/parse-smtp-template#4]
Is there anyway to set the from name using this module? I mean, say I set the mail to be sent from 'no-reply@mycompany.com'. Currently name shows as 'no-reply' (refer attached pic
![name](https://user-images.githubusercontent.com/41197333/75095323-88c2cd00-55b9-11ea-867a-18139891949f.png)
). Any way to make this show as 'My Company'?

**Comment by macarthuror** [comment]
Hello @ravikiranp123 🖖,
Sorry for taking so long to answer.

Yes, you can do it 👌 Just need to change the structure of the `fromAddress` parameter.
Let me show you with an example:
```javascript
const api = new ParseServer({
...
   emailAdapter: {
        module: 'parse-smtp-template',
        options: {
            host: process.env.SMTP_EMAIL_HOST,
            port: process.env.SMTP_EMAIL_PORT,
            user: process.env.SMTP_EMAIL_USER,
            password: process.env.SMTP_EMAIL_PASSWORD,
            fromAddress: `My Company <no-reply@mycompany.com>`
         ...
        }
   },
...
});

```

I hope you find it useful 😁 and thanks for give this repo a try.
