### ISSUE TITLE
Error: Greeting never received

### ISSUE THREAD

**Issue by suathh** [macarthuror/parse-smtp-template#6]
Hello I am trying to use template with below specs : 
```
emailAdapter: {
    module: 'parse-smtp-template',
    options: {
      port: 465,
      host: "mail.playm.io",
      user: "mail@playm.io",
      password: "***********",
      fromAddress: 'mail@playm.io'
    }
  }
```
But it gives this error

(node:4423) UnhandledPromiseRejectionWarning: Error: Greeting never received
    at SMTPConnection._formatError (/Users/suatkarabacak/Desktop/playm/node_modules/parse-smtp-template/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/Users/suatkarabacak/Desktop/playm/node_modules/parse-smtp-template/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)

**Comment by macarthuror** [comment]
Hello @suathh , could you tell me what version of parse and what version of smtp-template you are using. Please

**Comment by suathh** [comment]
Hello, I am using these versions 

```
"parse-server": "^3.7.2",
"parse-smtp-template": "^2.1.1"
```

**Comment by macarthuror** [comment]
I believe this issue is related with #7 and #10
Could you please update `parse-smtp-template` to the new versión and try it ?

**Comment by suathh** [comment]
I am using that versions but still getting the same error

```
"parse-server": "^3.10.0",
"parse-smtp-template": "^2.1.2",
```

**Comment by suathh** [comment]
I would like to help if you can give me some hints about problem

**Comment by frsisalima** [comment]
Hi, I have same problem but i changed port form 587 to 465 and add secure: true in the options, now it works correctly
